import json
import os
import sys
import types
import requests
import time
import numpy as np

# Add paths
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
sys.path.append(os.path.abspath(os.path.dirname(__file__)))

from prob import Evaluation

class CodeRefinerAgent:
    def __init__(self, api_endpoint, api_key, model):
        self.api_endpoint = api_endpoint
        self.api_key = api_key
        self.model = model

    def refine_code(self, original_code, objective, function_name="generate_giant_tour", error_msg=None, traceback_msg=None):
        print(f"\n[Agent] Starting refinement of {function_name} with objective: {objective}...")
        
        error_context = ""
        if error_msg:
            error_context = f"\nCRITICAL: The current code produced a 'None' result or crashed.\nError: {error_msg}\nTraceback: {traceback_msg if traceback_msg else 'N/A'}\nFIX THIS ERROR FIRST. Ensure the logic is robust and doesn't violate CVRP constraints."

        prompt = f"""
You are a Senior Optimization Engineer and Python Performance Expert. 
I have a '{function_name}' algorithm for CVRP generated by an evolutionary process. 
Current Objective (Fitness Score): {objective}
{error_context}

Original Code:
```python
{original_code}
```

Please refine this code to improve its OPTIMIZATION QUALITY and COMPUTATIONAL EFFICIENCY.
Focus on:
1. Advanced Heuristic Logic: Can you incorporate more sophisticated mathematical properties (e.g., better clustering, regret-based insertion, or angular considerations)?
2. Advanced Vectorization: Use NumPy operations to replace inner loops where possible.
3. Redundancy: Remove any repeated distance or demand calculations.

Provide the refined code inside a ```python ``` block. 
Also, provide a brief summary of your optimizations inside a {{ }} block.
Do not change the function signature.
"""

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": self.model,
            "messages": [{"role": "user", "content": prompt}]
        }

        try:
            url = f"{self.api_endpoint}/v1/chat/completions"
            response = requests.post(url, json=payload, headers=headers, timeout=60)
            res_json = response.json()
            content = res_json["choices"][0]["message"]["content"]
            
            import re
            refined_code = re.findall(r"```python\n(.*?)\n```", content, re.DOTALL)[0]
            summary = re.findall(r"\{(.*?)\}", content, re.DOTALL)[0]
            
            return refined_code, summary
        except Exception as e:
            print(f"Refinement error: {e}")
            return None, None

def main():
    # 1. Load best individual
    pop_file = os.path.join("results", "pops", "population_generation_0.json")
    with open(pop_file, 'r') as f:
        population = json.load(f)
    
    best_ind = population[0]
    
    # 2. Setup Refiner Agent
    # Re-using credentials from runEoH.py context
    api_key = "sk-c193ff0b07e3411d98aed240f791463f"
    api_endpoint = "api.deepseek.com"
    model = "deepseek-chat"
    
    refiner = CodeRefinerAgent(api_endpoint, api_key, model)
    
    # 3. Refine
    refined_code, summary = refiner.refine_code(best_ind['code'], best_ind['objective'])
    
    if refined_code:
        print(f"\n[Agent] Refinement Summary: {summary}")
        
        # 4. Evaluate Refined Code
        eva = Evaluation()
        from baseline_test import greedy_split # For context
        
        heuristic_module = types.ModuleType("refined_module")
        exec(refined_code, heuristic_module.__dict__)
        
        distances = []
        start_time = time.time()
        for instance in eva.instance_data:
            routes = heuristic_module.split_giant_tour(
                instance['giant_tour'], instance['demands'], instance['dist_matrix'], instance['capacity']
            )
            dist = eva.calculate_total_distance(routes, instance['dist_matrix'])
            distances.append(dist)
        end_time = time.time()
        
        avg_dist = np.mean(distances)
        print(f"\n[Comparison]")
        print(f"Original Objective: {best_ind['objective']:.4f}")
        print(f"Refined Objective:  {avg_dist:.4f}")
        print(f"Execution Time:     {end_time - start_time:.4f}s")
        
        # 5. Save refined code if better
        if avg_dist <= best_ind['objective']:
            save_path = os.path.join(os.path.dirname(__file__), "refined_best_alg.py")
            with open(save_path, "w") as f:
                f.write(refined_code)
            print(f"\n[Agent] Better code found and saved to {save_path}")

if __name__ == "__main__":
    main()
